name: Run benchmarks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    # if: ${{ github.repository == 'NX-AI/tirex-internal' }}
    if: False # Running the benchmarks on the github hosted runners takes too long (>1 hour)
    env:
      CI_RUN_BENCHMARKS: True
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          # cache: 'pip' # Caching didn't make the CI faster and cache is quite big (4GB)

      - run: pip install -e ".[test,gluonts,hfdataset]"
      - run: pytest tests/test_chronos_zs.py
